services:

  postgres:
    image: postgres:16
    container_name: softcost-db

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d softcostdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    environment:
      POSTGRES_DB: softcostdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: softcost-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/softcostdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: softcost-frontend
    depends_on:
      - backend
    environment:
      PORT: 4000
    ports:
      - "4200:4000"
