FROM node:20-alpine AS build
WORKDIR /workspace

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=build /workspace/dist ./dist
COPY --from=build /workspace/server.ts ./server.ts

EXPOSE 4000

CMD ["npm", "run", "serve:ssr:softcost-app"]