### Listar todas las regiones
GET http://localhost:8080/api/v1/cliente-service/clientes/regiones

###

### Listar todos los clientes (lista vacía al inicio)
GET http://localhost:8080/api/v1/cliente-service/clientes

###

### Crear un cliente
POST http://localhost:8080/api/v1/cliente-service/clientes
Content-Type: application/json

{
  "nombre": "Linus",
  "apellido": "Torvalds",
  "email": "linus@linux.org",
  "foto": "linus.jpg",
  "region": { "id": 1 }
}

###

### Crear otro cliente
POST http://localhost:8080/api/v1/cliente-service/clientes
Content-Type: application/json

{
  "nombre": "James",
  "apellido": "Gosling",
  "email": "james@java.com",
  "foto": "james.jpg",
  "region": { "id": 3 }
}

###

### Listar todos (ahora debe tener 2 clientes)
GET http://localhost:8080/api/v1/cliente-service/clientes

###

### Buscar por ID
GET http://localhost:8080/api/v1/cliente-service/clientes/1

###

### Actualizar el primer cliente
PUT http://localhost:8080/api/v1/cliente-service/clientes
Content-Type: application/json

{
  "id": 1,
  "nombre": "Linus",
  "apellido": "Torvalds",
  "email": "linus@kernel.org",
  "foto": "linus-updated.jpg",
  "region": { "id": 1 }
}

###

### Eliminar el primer cliente
DELETE http://localhost:8080/api/v1/cliente-service/clientes
Content-Type: application/json

{
  "id": 1
}

###

### Verificar que ya no existe (debe dar 404)
GET http://localhost:8080/api/v1/cliente-service/clientes/1


###
# curl http://localhost:8081/actuator/health
GET http://localhost:8081/actuator/health

###

# curl http://localhost:8081/actuator/metrics
GET http://localhost:8081/actuator/metrics

###

# curl "http://localhost:8081/actuator/metrics/hikaricp.connections.active"
GET http://localhost:8081/actuator/metrics/hikaricp.connections.active

###

# curl "http://localhost:8081/actuator/metrics/hikaricp.connections.idle"
GET http://localhost:8081/actuator/metrics/hikaricp.connections.idle

###

# curl http://localhost:8080/api/v1/cliente-service/clientes/regiones
GET http://localhost:8080/api/v1/cliente-service/clientes/regiones

###

# curl http://localhost:8080/api/v1/cliente-service/clientes
GET http://localhost:8080/api/v1/cliente-service/clientes

###